services:
  dbgatex_web:
    image: smartdb/dbgatex-web:${VERSION}
    container_name: dbagent_dbgatex_web
    restart: always
    networks:
      - dbagent
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
networks:
  dbagent:
    external: true
