services:
  dbmanager:
    image: zonesec/dbmanager:${VERSION}
    # image: ${REGISTRY:-docker.io}/zonesec/dbmanager:${VERSION}
    container_name: smartdb_dbmanager
    restart: always
    networks:
      - smartdb
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
networks:
  smartdb:
    external: true
