services:
  dbmanager:
    image: smartdb/dbmanager:${VERSION}
    container_name: dbagent_dbmanager
    restart: always
    networks:
      - dbagent
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
networks:
  dbagent:
    external: true
