services:
  mysql:
    image: mysql:8.0.40-debian
    container_name: dbagent_mysql
    restart: always
    networks:
      - dbagent
    # env_file:
    #   - ${CONFIG_ENV}
    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - DB_PORT=${DB_PORT}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      # - ${CONFIG_DIR}/mysql/my.cnf:/etc/mysql/my.cnf
      - ${VOLUME_DIR}/mysql/data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
networks:
  dbagent:
    external: true
