services:
  lb:
    image: nginx:1.25.3-alpine3.18
    container_name: smartdb_lb
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    networks:
      - smartdb
    # extra_hosts:
    #   - "HOST_DOMAIN:${NGINX_HOST_DOMAIN}"
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    volumes:
      - ${VOLUME_DIR}/nginx/data/log:/var/log/nginx
      - ${CONFIG_DIR}/nginx/smartdb.conf:/etc/nginx/conf.d/smartdb.conf
      - ${CONFIG_DIR}/nginx/ssl:/etc/nginx/ssl
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
networks:
  smartdb:
    external: true
